config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'pages#home'

        resources :recipes do
          resources :comments, only:[:create]
        end

        get '/signup', to: 'chefs#new'
        resources :chefs, except: [:new]
        get '/login', to: 'session#new'
        post '/login', to: 'session#create'
        delete 'logout', to: 'session#destroy'

    resources :ingredients, except: [:destroy]

    mount ActionCable.server => '/cable'

    get '/chat', to: 'chatrooms#show'
    resources :messages ,only: [:create]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
validates :name, presence: true
validates :description, presence: true, length: { minimum: 5, maximum: 500 }
belongs_to :chef
validates :chef_id, presence: true
default_scope -> {order(updated_at: :desc)}
has_many :recipe_ingredients
has_many :ingredients, through: :recipe_ingredients

has_many :comments, dependent: :destroy
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :sets_recipe, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

    def index
      @recipes = Recipe.paginate(page: params[:page], per_page: 5)
    end

    def new
      @recipe = Recipe.new
    end

    def show
      @comments = @recipe.comments.paginate(page: params[:page], per_page: 5)
      @comment = Comment.new
    end

    def create
      @recipe = Recipe.new(recipe_params)
      @recipe.chef = current_chef

        if @recipe.save
          flash[:success] = "Recipe was created!"
          redirect_to recipe_path(@recipe)
          else
          render 'new'
       end
     end

     def edit

     end

     def update

       if @recipe.update(recipe_params)
         flash[:success]= "Recipe was updated successfully!"
         redirect_to recipe_path(@recipe)
       else
         render 'edit'
       end
     end

     def destroy
       flash[:success] = "Recipe deleted successfully"
       redirect_to recipes_path
     end

     private

     def sets_recipe
       @recipe = Recipe.find(params[:id])
     end

     def recipe_params
       params.require(:recipe).permit(:name, :description, ingredient_ids:[])
     end

     def require_same_user
          if current_chef != @recipe.chef and !current_chef.admin?
            flash[:danger] = "You can only edit or delete your won recipe"
            redirect_to recipes_path
          end
     end
end

app/views/recipes/_comment.html.erb
<div align="center">
      <h3>Comments</h3>
        <hr>
  </div>
<div class="center">
    <div class="col-md-8 col-md-offset-2">
            <%= form_for([@recipe,@comment],remote: true, :html => {class: "form-horizontal", role: "form"}) do |f|%>
                <div class="form-group">
                    <div class="control-label col-md-2">
                    <%= f.label :Comment %>
                  </div>
                      <div class="col-md-8">
                      <%=f.text_area :description, rows:3, class: "form-control", placeholder: "Entre your comments"%>
                      </div>
                </div>

              </div>
                <div class="from-group">
                  <div class="col-md-offset-4 col-md-4 ">
                    <%=f.submit class: "btn btn-primary btn-large" %>
                  </div>
                </div>
            <%end%>
</div>

app/views/recipes/_form.html.erb
<div class="row">
          <div class="col-md-12">
                  <%= form_for(@recipe, :html => {class: "form-horizontal", role: "form"}) do |f|%>
                  <div class="form-group">
                      <div class="control-label col-md-2">
                              <%= f.label :neme%>
                      </div>

                      <div class="col-md-8">
                        <%= f.text_field :name, class: "form-control" , placeholder: "Name of recipe", autofocus:true%>
                      </div>
                  </div>

                <div class="form-group">
                    <div class="control-label col-md-2">
                      <%= f.label :description %>
                    </div>

                    <div class="col-md-8">
                      <%=f.text_area :description, rows: 10, class: "form-control", placeholder: "Enter steps to create recipe"%>
                    </div>
                </div>
                <div class="form-group">
                  <div class="row">
                      <div class="col-md-offset-2 col-md-8">
                        <%=f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |cb|%>
                          <%cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class:"checkbox") + cb.text}%>
                        <%end%>
                      </div>
                  </div>
                </div>
                <div class="from-group">
                  <div class="col-md-offset-2 col-md-10">
                    <%=f.submit class: "btn btn-primary btn-large" %>
                  </div>
                </div>
          </div>
              <%end%>
            <div class="col-md-offset-4 col-md-10">
              [<%= link_to "Cancel request and return recipes listeing", recipes_path %>]
              </div>

  </div>

app/views/recipes/_recipe.html.erb
<% obj.each do |recipe|%>
<div class="row">
        <div class="col-md-2">

            <section class= "center">
              <%= gravater_for(recipe.chef, size: 120) %>
            </section>
        </div>

      <div class="col-md-8 well">
            <h4><%=link_to recipe.name, recipe_path(recipe)%>
            <p><%= truncate(recipe.description, length: 150)%>  </h4>
               <%if recipe.ingredients.any?%>
               <p>Ingredient: <%=  render recipe.ingredients %></p>
               <%end%>
            <small><%= time_ago_in_words(recipe.created_at)%> ago by <%= link_to recipe.chef.chefname, chef_path(recipe.chef)%>
            | <%= pluralize(recipe.comments.count, "Comments")%> </small></p>

                    <%if logged_in? && (current_chef == recipe.chef || current_chef.admin?) %>
                         <div class="recipe_action">
                          <%= link_to "Edit this recipe", edit_recipe_path(recipe), class: "btn btn-xs btn-warning" %>
                          <%= link_to "Delete this item", recipe_path(recipe), method: :delete,
                                                      data: {confirm: "Are you sure to delete this item?"},
                                                      class: "btn btn-xs btn-danger" %>
                  </div>
                    <%end%>
      </div>
</div>
<%end%>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: "Edit recipe" %>
<!-- error message while edit recipes without any values -->
<%= render 'shared/error', obj:@recipe %>
<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render'shared/page_title', title: "Showing all recipes" %>
  <div align= "center">
  <%=will_paginate%>
</div>
<%= render 'recipe', obj:@recipes%>
  <div align= "center">
  <%=will_paginate%>
</div>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: "Create new recipe" %>
<%= render 'shared/error', obj:@recipe %>
<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>
<div class="row">
      <div class=" well col-md-8 col-md-offset-2">
            <h4 class="center description"> <strong> Steps: </strong></h4>
            <hr />
            <%= simple_format(@recipe.description)%>
            <hr />

            <%if @recipe.ingredients.any?%>
            <p>Ingredients: <%=render @recipe.ingredients%></p>
            <%end%>
            <div class="pull-right">
              <p class= "center"
                <em> Created by: </em>
                </p>
                <p class = "center">
              <%= link_to gravater_for(@recipe.chef), chef_path(@recipe.chef) %>

              <small> <%= @recipe.chef.chefname.capitalize%> </small> </p>
             <div class="pull-right"> Created: <%= time_ago_in_words(@recipe.created_at)%> ago</div>

            </div>

            <%if logged_in? && (current_chef == @recipe.chef || current_chef.admin?) %>
            <div class="recipe_action">
              <%= link_to "Edit this recipe", edit_recipe_path(@recipe), class: "btn btn-xs btn-warning" %>
              <%= link_to "All recipes", recipes_path, class: "btn btn-xs btn-primary" %>
              <%= link_to "Delete this item", recipe_path(@recipe), method: :delete,
                                              data: {confirm: "Are you sure to delete this item?"},
                                              class: "btn btn-xs btn-danger" %>
            </div>
            <%else%>
            <%= link_to "All recipes", recipes_path, class: "btn btn-xs btn-primary" %>
            <%end%>

        </div>
</div>

<%if logged_in?%>
<div align="center">
   <%= render 'comment'%>
</div>

<%end%>
<% if @recipe.comments !=0 %>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h3> Prior comments:</h3>
    <div id="messages">
      <%= render partial: 'comments/comments', object: @comments%>
    </div>
  </div>
</div>
<% else%>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h3> No comments yet</h3>
  </div>
</div>
<%end%>