config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'pages#home'

        resources :recipes do
          resources :comments, only:[:create]
        end

        get '/signup', to: 'chefs#new'
        resources :chefs, except: [:new]
        get '/login', to: 'session#new'
        post '/login', to: 'session#create'
        delete 'logout', to: 'session#destroy'

    resources :ingredients, except: [:destroy]

    mount ActionCable.server => '/cable'

    get '/chat', to: 'chatrooms#show'
    resources :messages ,only: [:create]
end

app/models/ingredient.rb
class Ingredient<ApplicationRecord
validates :name, presence: true, length: { minimum: 3, maximum: 25 }
validates_uniqueness_of :name

has_many :recipe_ingredients
has_many :recipes, through: :recipe_ingredients
end

app/controllers/ingredients_controller.rb
class IngredientsController <  ApplicationController
  before_action :set_ingredient, only: [:edit, :update, :show]
  before_action :require_admin ,except:[:index, :show]
    def new
      @ingredient = Ingredient.new
    end

    def create
      @ingredient = Ingredient.new(ingredient_params)
      if @ingredient.save
        flash[:success]= "Ingredient was successfully created"
        redirect_to ingredient_path(@ingredient)
      else
        render 'new'
      end
    end

    def edit

    end

    def update
      if @ingredient.update(ingredient_params)
        flash[:success] = "Ingredient was successfully updated"
        redirect_to @ingredient
      else
        render 'edit'
      end
    end

    def show
        @ingredient_recipes = @ingredient.recipes.paginate(page: params[:page], per_page:5)
    end

    def index
      @ingredients = Ingredient.paginate(page: params[:page],per_page: 5)
    end

    private

    def ingredient_params
      params.require(:ingredient).permit(:name)

    end

    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    def require_admin
      if !logged_in? ||(logged_in? && !current_chef.admin?)
        flash[:danger]= "Only admin user can perform this action"
        redirect_to ingredients_path
      end
    end

end

app/views/ingredients/_form.html.erb
<%= render 'shared/error', obj: @ingredient%>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@ingredient, :html => {class: "form-horizontal", role: "form"}) do |f|%>
<div class="form-group">
    <div class="control-label col-md-2">
        <%= f.label :name, "Name"%>
    </div>
    <div class="col-md-8">
      <%= f.text_field :name, class: "form-control" , placeholder: "Name of chefs", autofocus:true%>
    </div>
</div>

<div class="from-group">
  <div class="col-md-offset-2 col-md-10">
    <%=f.submit(@ingredient.new_record? ? "Add Ingredient" : "Update Ingredient", class: "btn btn-primary btn-large") %>
  </div>
</div>

  </div>
    <%end%>
    <div class="col-md-offset-4 col-md-10">
      [<%= link_to "Cancel request and return home page", ingredients_path %>]
      </div>

  </div>

app/views/ingredients/_ingredient.html.erb
<span class="badge"><%= link_to ingredient.name, ingredient_path(ingredient)%> &nbsp; </span>

app/views/ingredients/edit.html.erb
<%= render 'shared/page_title', title: "Edit ingredient"%>
<%=render 'form'%>

app/views/ingredients/index.html.erb
<%= render'shared/page_title', title: "Avaiable ingredients" %>
<div align= "center">
<%=will_paginate%>
</div>

<div align= "center">
  <% @ingredients.each do |ing|%>
    <ul class = "listing">
      <div class="row">
      <div class="well col-md-4 col-md-offset-4">
          <li class="chef-title"><%= link_to ing.name.capitalize, ingredient_path(ing) %></li>
          <% if ing.recipes.count != 0 %>
          <li><small><%= pluralize(ing.recipes.count, "recipe")if ing.recipes %></small></li>
              <% if logged_in? && current_chef.admin? %>
              <li><%=link_to "Edit this ingredient", ingredient_path(ing) %></li>
              <%end%>
          <%else%>
          <h6> Not yet used in any recipe </h6>
          <% end %>
      </div>
    </div>
    </ul>
<%end%>
</div>
    <div align= "center">
    <%=will_paginate%>
  </div>

app/views/ingredients/new.html.erb
<%= render 'shared/page_title', title: "Create new ingredient"%>
<%=render 'form'%>

app/views/ingredients/show.html.erb
<%= render'shared/page_title', title: "Ingredient" %>
<div class="row">
<div class="well col-md-6 col-md-offset-3">
      <h4 class = "center description">
      <strong> Ingredient Name:</strong> </h4>
         <h5 align="center">  <strong> <%= @ingredient.name%></strong></h5>
        <hr>

      <%if logged_in? && (current_chef == @chef || current_chef.admin?) %>
      <div class="pull-right">
        <%=link_to "Edit ingredient", edit_ingredient_path(@ingredient), class: "btn btn-xs btn-warning"%>
        <%= link_to "Ingredient Home", ingredients_path, class:"btn btn-xs btn-primary" %>
        <%end%>
      </div>
</div>

</div>
<div class="center">
  <%  will_paginate @ingredient_recipes%>
</div>
    <%if @ingredient.recipes.count != 0%>

    <h4 align= "center"> <strong><%= @ingredient.name %>'s recipes</strong></h4>
    <hr>

    <%= render 'recipes/recipe', obj: @ingredient.recipes %>

    <%else%>
    <h4> Not yet added any recipe </h4>
    <%end%>