config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'pages#home'

        resources :recipes do
          resources :comments, only:[:create]
        end

        get '/signup', to: 'chefs#new'
        resources :chefs, except: [:new]
        get '/login', to: 'session#new'
        post '/login', to: 'session#create'
        delete 'logout', to: 'session#destroy'

    resources :ingredients, except: [:destroy]

    mount ActionCable.server => '/cable'

    get '/chat', to: 'chatrooms#show'
    resources :messages ,only: [:create]
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="page-footer font-small teal pt-4">

  <!-- Footer Text -->
  <div class="container-fluid text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-6 mt-md-0 mt-3">

        <!-- Content -->
        <h5 class="text-uppercase font-weight-bold">About us</h5>
        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Expedita sapiente sint, nulla, nihil
          repudiandae commodi voluptatibus corrupti animi sequi aliquid magnam debitis, maxime quam recusandae
          harum esse fugiat. Itaque, culpa?</p>

      </div>
      <!-- Grid column -->

    

      <!-- Grid column -->
      <div class="col-md-6 mb-md-0 mb-3">

        <!-- Content -->
        <h5 class="text-uppercase font-weight-bold">contact us</h5>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Optio deserunt fuga perferendis modi earum
          commodi aperiam temporibus quod nulla nesciunt aliquid debitis ullam omnis quos ipsam, aspernatur id
          excepturi hic.</p>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Text -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <%=link_to "myrecipe.com", root_path%>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <% flash.each do |name, msg|%>
    <div class="alert alert-<%= name %>">
      <a href="#" class = "close" data-dismiss= "alert"> &#215;</a>
      <%= msg %>
    <%end%>
    </div>
  </div>

</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "MyRecepie", root_path, class:"navbar-brand", id:"logo"  %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Actions <span class="caret"></span></a>
            <ul class="dropdown-menu">
            <li class="active"><%= link_to "Chefs", chefs_path%></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "All recipes", recipes_path %></li>
            <li role="separator" class="divider"></li>
            <li><%=link_to "Ingredients", ingredients_path%></li>
            </ul>
        </li>
        <%if logged_in? %>
        <li class="dropdown">

          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Recipes <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Create new recipe", new_recipe_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "All recipes", recipes_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "ChefChat", chat_path %></li>

          </ul>
        </li>


        <li class="dropdown">

          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Ingredient <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "All Ingredients", ingredients_path %></li>
              <%Ingredient.all.each do |ingredient|%>
              <li><%=link_to ingredient.name.capitalize, ingredient_path(ingredient)%></li>
              <%end%>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Create new", new_ingredient_path %></li>
            <%end%>
          </ul>
        </li>

      </ul>
      <%= form_tag(chefs_path, class:"navbar-form navbar-left", role: "search", method: :get) do %>

        <div class="form-group">
          <%= text_field_tag :term, params[:term],class:"form-control", placeholder:"Search", autocomplete:"off" %>
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      <%end%>
      <ul class="nav navbar-nav navbar-right">

        <%if logged_in?%>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_chef.chefname%> <%="| Admin" if current_chef.admin?%> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", chef_path(current_chef) %></li>
            <li><%= link_to "Edit Profile", edit_chef_path(current_chef) %></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li> <%=link_to "Logout", logout_path, method: :delete%> </a></li>
            <%else%>
              <li><%= link_to "Login", login_path %></li>
            <%end%>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myrecepie</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>

  <%= render 'layouts/navbar' %>
  <%= render 'layouts/messages' %>


  <div class="container">
      <%= yield %>
  <%= render 'layouts/footer'%>

  </div>



  </body>

</html>